package com.b3.rbl.executeruleengine;

import com.b3.rbl.executeruleengine.incomeDetails;
 
rule "Rs 0.0 – Rs 2.5 Lakhs"
    when
        incomeDetail: incomeDetails(incomeInRupees > 0 && incomeInRupees < 250000)
    then
    System.out.println("Less Than 250000");
        incomeDetail.setIncomeTaxPercentage(0.0);
end
 
rule "Rs 2.5 lakhs - Rs 5.0 Lakhs"
    when
        incomeDetail: incomeDetails(incomeInRupees > 250000 && incomeInRupees < 500000)
    then
    System.out.println("Less Than 500000");
        incomeDetail.setIncomeTaxPercentage(5.0);
end
rule "Rs. 5.00 lakhs- Rs 7.5 Lakhs"
    when
        incomeDetail: incomeDetails(incomeInRupees > 500000 && incomeInRupees < 750000)
    then
    System.out.println("Less Than 750000");
        incomeDetail.setIncomeTaxPercentage(10.0);
end
rule "Rs 7.5 lakhs – Rs 10.00 Lakhs"
    when
        incomeDetail: incomeDetails(incomeInRupees > 750000 && incomeInRupees < 1000000)
    then
    System.out.println("Less Than 1000000");
        incomeDetail.setIncomeTaxPercentage(15.0);
end
rule "Rs 10.00 lakhs – Rs. 12.50 Lakhs"
    when
        incomeDetail: incomeDetails(incomeInRupees > 1000000 && incomeInRupees < 1250000)
    then
    System.out.println("Less Than 1250000");
        incomeDetail.setIncomeTaxPercentage(20.0);
end
rule "Rs. 12.5 lakhs- Rs. 15.00 Lakhs"
    when
        incomeDetail: incomeDetails(incomeInRupees > 1250000 && incomeInRupees < 1500000)
    then
    System.out.println("Less Than 1500000");
        incomeDetail.setIncomeTaxPercentage(25.0);
end
rule "> Rs. 15 Lakhs"
    when
        incomeDetail: incomeDetails(incomeInRupees > 1500000)
    then
    System.out.println("Greater Than 1500000");
        incomeDetail.setIncomeTaxPercentage(30.0);
end
