package com.b3.rbl.executeruleengine.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AgentDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public AgentDetails() {
    }




}