package com.b3.rbl.executeruleengine.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AgentCalculationModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Agent Code")
	private java.lang.String agentCode;
	@org.kie.api.definition.type.Label("FYC Amount")
	private java.lang.Double fycAmount;
	@org.kie.api.definition.type.Label("Policy No")
	private java.lang.String policyNo;

	@org.kie.api.definition.type.Label("Agent Position")
	private java.lang.String agentPosition;

	public AgentCalculationModel() {
	}

	public java.lang.String getAgentCode() {
		return this.agentCode;
	}

	public void setAgentCode(java.lang.String agentCode) {
		this.agentCode = agentCode;
	}

	public java.lang.Double getFycAmount() {
		return this.fycAmount;
	}

	public void setFycAmount(java.lang.Double fycAmount) {
		this.fycAmount = fycAmount;
	}

	public java.lang.String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(java.lang.String policyNo) {
		this.policyNo = policyNo;
	}

	public java.lang.String getAgentPosition() {
		return this.agentPosition;
	}

	public void setAgentPosition(java.lang.String agentPosition) {
		this.agentPosition = agentPosition;
	}

	public java.lang.String toString() {
		return "Agent Code : " + this.agentCode + ", Position : "
				+ this.agentPosition + ", Policy No : " + this.policyNo
				+ ", Fyc :" + this.fycAmount;
	}

	public AgentCalculationModel(java.lang.String agentCode,
			java.lang.Double fycAmount, java.lang.String policyNo,
			java.lang.String agentPosition) {
		this.agentCode = agentCode;
		this.fycAmount = fycAmount;
		this.policyNo = policyNo;
		this.agentPosition = agentPosition;
	}

}