package com.b3.rbl.executeruleengine.executeruleengine;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class TestObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TESTOBJECT_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "TESTOBJECT_ID_SEQ", name = "TESTOBJECT_ID_GENERATOR")
    private java.lang.Long id;

    public TestObject() {
    }
    
    public TestObject(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}