package com.b3.rbl.executeruleengine;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AgentDetail implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Agent Code")
	private java.lang.String agentCode;
	@org.kie.api.definition.type.Label("Policy Code")
	private java.lang.String policyCode;
	@org.kie.api.definition.type.Label("fyc")
	private java.lang.Double fyc;

	@org.kie.api.definition.type.Label(value = "Agent Position")
	private java.lang.String agentPosition;

	public agentDetail() {
	}

	public java.lang.String getAgentCode() {
		return this.agentCode;
	}

	public void setAgentCode(java.lang.String agentCode) {
		this.agentCode = agentCode;
	}

	public java.lang.String getPolicyCode() {
		return this.policyCode;
	}

	public void setPolicyCode(java.lang.String policyCode) {
		this.policyCode = policyCode;
	}

	public java.lang.Double getFyc() {
		return this.fyc;
	}

	public void setFyc(java.lang.Double fyc) {
		this.fyc = fyc;
	}

	public agentDetail(java.lang.String agentCode, java.lang.String policyCode,
			java.lang.Double fyc) {
		this.agentCode = agentCode;
		this.policyCode = policyCode;
		this.fyc = fyc;
	}

	public java.lang.String getAgentPosition() {
		return this.agentPosition;
	}

	public void setAgentPosition(java.lang.String agentPosition) {
		this.agentPosition = agentPosition;
	}

	public AgentDetail() {
	}

	public AgentDetail(java.lang.String agentCode, java.lang.String policyCode,
			java.lang.Double fyc, java.lang.String agentPosition) {
		this.agentCode = agentCode;
		this.policyCode = policyCode;
		this.fyc = fyc;
		this.agentPosition = agentPosition;
	}

}