package com.b3.rbl.executeruleengine;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AgentResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("agentCode")
	private java.lang.String agentCode;
	@org.kie.api.definition.type.Label("FYC Amount")
	private java.lang.Double fycAmount;
	@org.kie.api.definition.type.Label("Bonus Rate")
	private Double bonusRate;

	@org.kie.api.definition.type.Label("Persistency Controller")
	private java.lang.Double persistencyController;

	@org.kie.api.definition.type.Label("Monthly Bonus")
	private java.lang.Double monthlyBonus;

	@org.kie.api.definition.type.Label("Calculation Date")
	private java.util.Date calculationDate;

	public AgentResult() {
	}

	public java.lang.String getAgentCode() {
		return this.agentCode;
	}

	public void setAgentCode(java.lang.String agentCode) {
		this.agentCode = agentCode;
	}

	public java.lang.Double getFycAmount() {
		return this.fycAmount;
	}

	public void setFycAmount(java.lang.Double fycAmount) {
		this.fycAmount = fycAmount;
	}

	public java.lang.Double getBonusRate() {
		return this.bonusRate;
	}

	public void setBonusRate(java.lang.Double bonusRate) {
		this.bonusRate = bonusRate;
	}

	public java.lang.Double getPersistencyController() {
		return this.persistencyController;
	}

	public void setPersistencyController(java.lang.Double persistencyController) {
		this.persistencyController = persistencyController;
	}

	public java.lang.Double getMonthlyBonus() {
		return this.monthlyBonus;
	}

	public void setMonthlyBonus(java.lang.Double monthlyBonus) {
		this.monthlyBonus = monthlyBonus;
	}

	public java.util.Date getCalculationDate() {
		return this.calculationDate;
	}

	public void setCalculationDate(java.util.Date calculationDate) {
		this.calculationDate = calculationDate;
	}

	public AgentResult(java.lang.String agentCode, java.lang.Double fycAmount,
			java.lang.Double bonusRate, java.lang.Double persistencyController,
			java.lang.Double monthlyBonus, java.util.Date calculationDate,
			java.util.List<com.b3.rbl.executeruleengine.AgentDetail> agentDetail) {
		this.agentCode = agentCode;
		this.fycAmount = fycAmount;
		this.bonusRate = bonusRate;
		this.persistencyController = persistencyController;
		this.monthlyBonus = monthlyBonus;
		this.calculationDate = calculationDate;
		this.agentDetail = agentDetail;
	}

	public AgentResult(java.lang.String agentCode, java.lang.Double fycAmount,
			java.lang.Double bonusRate, java.lang.Double persistencyController,
			java.lang.Double monthlyBonus, java.util.Date calculationDate) {
		this.agentCode = agentCode;
		this.fycAmount = fycAmount;
		this.bonusRate = bonusRate;
		this.persistencyController = persistencyController;
		this.monthlyBonus = monthlyBonus;
		this.calculationDate = calculationDate;
	}

}