package com.b3.rbl.executeruleengine;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class agentDetail implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public agentDetail() {
    }




}