package com.b3.rbl.executeruleengine;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IncomeDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Income In Rupees")
	private java.lang.Integer incomeInRupees;
	@org.kie.api.definition.type.Label("Income Tax Percentage")
	private java.lang.Double incomeTaxPercentage;

	@org.kie.api.definition.type.Label(value = "Execute Rule")
	private boolean executeRule;

	public IncomeDetails() {
	}

	public java.lang.Integer getIncomeInRupees() {
		return this.incomeInRupees;
	}

	public void setIncomeInRupees(java.lang.Integer incomeInRupees) {
		this.incomeInRupees = incomeInRupees;
	}

	public java.lang.Double getIncomeTaxPercentage() {
		return this.incomeTaxPercentage;
	}

	public void setIncomeTaxPercentage(java.lang.Double incomeTaxPercentage) {
		this.incomeTaxPercentage = incomeTaxPercentage;
	}

	public boolean isExecuteRule() {
		return this.executeRule;
	}

	public void setExecuteRule(boolean executeRule) {
		this.executeRule = executeRule;
	}

	public IncomeDetails(java.lang.Integer incomeInRupees,
			java.lang.Double incomeTaxPercentage, boolean executeRule) {
		this.incomeInRupees = incomeInRupees;
		this.incomeTaxPercentage = incomeTaxPercentage;
		this.executeRule = executeRule;
	}

}